import type { Metadata } from "next";
import "@/styles/globals.css";
import { DM_Sans } from "next/font/google";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const walone_bold = localFont({
  src: "../../../public/fonts/Z06-Walone-Bold.ttf",
  display: "swap",
  variable: "--font-z06-walone-bold",
});

export const metadata: Metadata = {
  title: "Travel Booking",
  description: "Generated by Mya Hmue Eaindra Nwe",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`antialiased 
    ${dmSans.variable} 
    ${walone_bold.variable} 
  `}
        style={{
          fontFamily:
            locale === "mm"
              ? "var(--font-z06-walone-bold)"
              : "var(--font-dm-sans)",
        }}
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
